### ISSUE TITLE
Append with no arguments causes a panic in the client

### ISSUE THREAD

**Issue by dburkart** [dburkart/fossil#69]
What the title says:

```
> append
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/dburkart/fossil/pkg/repl.ParseREPLCommand({0xc000161638, 0x6, 0x20})
	/home/dburkart/Projects/fossil/pkg/repl/parser.go:45 +0xa0f
github.com/dburkart/fossil/cmd/fossil/client.readlinePrompt({{0x0, {0x7ffcf67ac47f, 0x10}, {0xa4f743, 0x7}}, 0xc000128780})
	/home/dburkart/Projects/fossil/cmd/fossil/client/client.go:169 +0xe85
github.com/dburkart/fossil/cmd/fossil/client.glob..func1(0xf35940?, {0xa4e5db?, 0x2?, 0x2?})
	/home/dburkart/Projects/fossil/cmd/fossil/client/client.go:58 +0x3f2
github.com/spf13/cobra.(*Command).execute(0xf35940, {0xc000143320, 0x2, 0x2})
	/home/dburkart/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xf35660)
	/home/dburkart/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/dburkart/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/dburkart/fossil/cmd/fossil.Execute()
	/home/dburkart/Projects/fossil/cmd/fossil/root.go:56 +0x25
main.main()
	/home/dburkart/Projects/fossil/main.go:14 +0x17
```

**Comment by dburkart** [comment]
Fixed by 7c476ed912dcb50d
